services:
  finances.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000 # 🔹 Remove HTTPS e força apenas HTTP
    ports:
      - "5050:5000"
      - "5051:5001"

  finances.consumer:
    environment:
      - DOTNET_ENVIRONMENT=Production
